package mocks

import "github.com/vjftw/orchestrate/commander/domain/user"
import "github.com/stretchr/testify/mock"

// Provider is an autogenerated mock type for the Provider type
type Provider struct {
	mock.Mock
}

// New provides a mock function with given fields:
func (_m *Provider) New() *user.User {
	ret := _m.Called()

	var r0 *user.User
	if rf, ok := ret.Get(0).(func() *user.User); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.User)
		}
	}

	return r0
}
