// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/vjftw/orchestrate/commander/resolvers (interfaces: IUser)

package resolvers

import (
	io "io"

	gomock "github.com/golang/mock/gomock"
	models "github.com/vjftw/orchestrate/commander/models"
)

// Mock of IUser interface
type MockIUser struct {
	ctrl     *gomock.Controller
	recorder *_MockIUserRecorder
}

// Recorder for MockIUser (not exported)
type _MockIUserRecorder struct {
	mock *MockIUser
}

func NewMockIUser(ctrl *gomock.Controller) *MockIUser {
	mock := &MockIUser{ctrl: ctrl}
	mock.recorder = &_MockIUserRecorder{mock}
	return mock
}

func (_m *MockIUser) EXPECT() *_MockIUserRecorder {
	return _m.recorder
}

func (_m *MockIUser) FromRequest(_param0 *models.User, _param1 io.ReadCloser) error {
	ret := _m.ctrl.Call(_m, "FromRequest", _param0, _param1)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockIUserRecorder) FromRequest(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "FromRequest", arg0, arg1)
}
