// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/vjftw/orchestrate/master/providers (interfaces: IUser)

package providers

import (
	gomock "github.com/golang/mock/gomock"
	models "github.com/vjftw/orchestrate/master/models"
)

// Mock of IUser interface
type MockIUser struct {
	ctrl     *gomock.Controller
	recorder *_MockIUserRecorder
}

// Recorder for MockIUser (not exported)
type _MockIUserRecorder struct {
	mock *MockIUser
}

func NewMockIUser(ctrl *gomock.Controller) *MockIUser {
	mock := &MockIUser{ctrl: ctrl}
	mock.recorder = &_MockIUserRecorder{mock}
	return mock
}

func (_m *MockIUser) EXPECT() *_MockIUserRecorder {
	return _m.recorder
}

func (_m *MockIUser) New() *models.User {
	ret := _m.ctrl.Call(_m, "New")
	ret0, _ := ret[0].(*models.User)
	return ret0
}

func (_mr *_MockIUserRecorder) New() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "New")
}
