package mocks

import "github.com/vjftw/orchestrate/commander/persisters"
import "github.com/stretchr/testify/mock"

// Persister is an autogenerated mock type for the Persister type
type Persister struct {
	mock.Mock
}

// Delete provides a mock function with given fields: _a0
func (_m *Persister) Delete(_a0 persisters.Persistable) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(persisters.Persistable) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetInto provides a mock function with given fields: _a0, _a1, _a2
func (_m *Persister) GetInto(_a0 persisters.Persistable, _a1 interface{}, _a2 ...interface{}) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(persisters.Persistable, interface{}, ...interface{}) error); ok {
		r0 = rf(_a0, _a1, _a2...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Save provides a mock function with given fields: _a0
func (_m *Persister) Save(_a0 persisters.Persistable) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(persisters.Persistable) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
