package mocks

import "github.com/stretchr/testify/mock"

import "github.com/gorilla/mux"

// Controller is an autogenerated mock type for the Controller type
type Controller struct {
	mock.Mock
}

// AddRoutes provides a mock function with given fields: _a0
func (_m *Controller) AddRoutes(_a0 mux.Router) {
	_m.Called(_a0)
}
