package mocks

import "github.com/stretchr/testify/mock"

// Persister is an autogenerated mock type for the Persister type
type Persister struct {
	mock.Mock
}

// Save provides a mock function with given fields: _a0
func (_m *Persister) Save(_a0 interface{}) {
	_m.Called(_a0)
}
