// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/vjftw/orchestrate/commander/managers (interfaces: IManager)

package managers

import (
	gomock "github.com/golang/mock/gomock"
	models "github.com/vjftw/orchestrate/commander/models"
)

// Mock of IManager interface
type MockIManager struct {
	ctrl     *gomock.Controller
	recorder *_MockIManagerRecorder
}

// Recorder for MockIManager (not exported)
type _MockIManagerRecorder struct {
	mock *MockIManager
}

func NewMockIManager(ctrl *gomock.Controller) *MockIManager {
	mock := &MockIManager{ctrl: ctrl}
	mock.recorder = &_MockIManagerRecorder{mock}
	return mock
}

func (_m *MockIManager) EXPECT() *_MockIManagerRecorder {
	return _m.recorder
}

func (_m *MockIManager) Delete(_param0 models.IModel) error {
	ret := _m.ctrl.Call(_m, "Delete", _param0)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockIManagerRecorder) Delete(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Delete", arg0)
}

func (_m *MockIManager) GetInto(_param0 models.IModel, _param1 interface{}, _param2 ...interface{}) error {
	_s := []interface{}{_param0, _param1}
	for _, _x := range _param2 {
		_s = append(_s, _x)
	}
	ret := _m.ctrl.Call(_m, "GetInto", _s...)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockIManagerRecorder) GetInto(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	_s := append([]interface{}{arg0, arg1}, arg2...)
	return _mr.mock.ctrl.RecordCall(_mr.mock, "GetInto", _s...)
}

func (_m *MockIManager) Save(_param0 models.IModel) error {
	ret := _m.ctrl.Call(_m, "Save", _param0)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockIManagerRecorder) Save(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Save", arg0)
}
