package mocks

import (
	"io"

	"github.com/stretchr/testify/mock"
	"github.com/vjftw/orchestrate/commander/domain/cadetGroup"
)

// Resolver is an autogenerated mock type for the Resolver type
type Resolver struct {
	mock.Mock
}

// FromRequest provides a mock function with given fields: _a0, _a1
func (_m *Resolver) FromRequest(_a0 *cadetGroup.CadetGroup, _a1 io.ReadCloser) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(*cadetGroup.CadetGroup, io.ReadCloser) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
