// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/vjftw/orchestrate/master/validators (interfaces: Validator)

package validators

import (
	gomock "github.com/golang/mock/gomock"
	messages "github.com/vjftw/orchestrate/master/messages"
	models "github.com/vjftw/orchestrate/master/models"
)

// Mock of Validator interface
type MockValidator struct {
	ctrl     *gomock.Controller
	recorder *_MockValidatorRecorder
}

// Recorder for MockValidator (not exported)
type _MockValidatorRecorder struct {
	mock *MockValidator
}

func NewMockValidator(ctrl *gomock.Controller) *MockValidator {
	mock := &MockValidator{ctrl: ctrl}
	mock.recorder = &_MockValidatorRecorder{mock}
	return mock
}

func (_m *MockValidator) EXPECT() *_MockValidatorRecorder {
	return _m.recorder
}

func (_m *MockValidator) Validate(_param0 models.Model) (bool, *messages.ValidationMessage) {
	ret := _m.ctrl.Call(_m, "Validate", _param0)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(*messages.ValidationMessage)
	return ret0, ret1
}

func (_mr *_MockValidatorRecorder) Validate(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Validate", arg0)
}
